#!/usr/bin/env bash
# Install my dotfiles
set -ex

git clone --depth 1 https://github.com/pietvanzoen/dotfiles.git "$HOME/dotfiles"

cd "$HOME/dotfiles"

CONFIRM_ALL=true ./_scripts/bootstrap

./install
